# Generated by Django 5.0.7 on 2024-12-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "network_administrator",
            "0002_alter_comment_options_rename_title_comment_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="anonymous_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
