# Generated by Django 5.0.7 on 2024-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_administrator", "0004_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="session_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
