# Generated by Django 5.0.7 on 2024-12-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_administrator", "0007_alter_like_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
